코드 최적화
lekakid/ArcaRefresher pull request #105
Opened 2022-11-26 11:27 UTC by green1052

2022-11-26 14:40 UTC, lekakid requested changes
App.jsx, func/url.jsx 가 마무리되면 받겠습니다

2022-11-26 14:40 UTC, lekakid commented on src/meta.json
> +  "run-at": "document-body",
Violentmonkey에서 안될줄 알았는데... 아무 문제 없이 동작하네요?
??
그래서 이부분은 그냥 받기로 했습니다.

2022-11-26 14:52 UTC, green1052 commented on src/func/url.jsx
> -  const urlQuery = type ? `?type=${type}` : '?';
이건 테스트를 해봐야될거같은데

2023-01-01 05:52 UTC, lekakid commented on src/func/url.jsx
> -  const urlQuery = type ? `?type=${type}` : '?';
이 부분 그냥 받겠습니다. 대부분은 다운로드 에러나는 사람 환경 예상을 못해서 버그가 나봐야 알기도 하고

2023-01-01 05:53 UTC, lekakid approved these changes

2023-01-01 05:54 UTC, merged